version: '3.8'

services:
  focj-db:
    image: mysql:8.0
    container_name: focj-db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    ports:
      - "6501:3306"
    volumes:
      - focj_mysql_data:/var/lib/mysql
      - ./sql/registrations_table.sql:/docker-entrypoint-initdb.d/01_registrations.sql
      - ./sql/schema_mysql.sql:/docker-entrypoint-initdb.d/02_schema.sql
      - ./sql/initial_data.sql:/docker-entrypoint-initdb.d/03_initial_data.sql
    networks:
      - focj_network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  focj-web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: focj-web
    restart: always
    ports:
      - "6500:80"
    environment:
      DB_TYPE: mysql
      DB_HOST: focj-db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./php-app:/var/www/html
      - ./registration-form:/var/www/html/templates/registration-form
      - ./member-management:/var/www/html/templates/member-management
    depends_on:
      focj-db:
        condition: service_healthy
    networks:
      - focj_network

  focj-phpmyadmin:
    image: phpmyadmin:latest
    container_name: focj-phpmyadmin
    restart: always
    ports:
      - "6502:80"
    environment:
      PMA_HOST: focj-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 50M
    depends_on:
      - focj-db
    networks:
      - focj_network

volumes:
  focj_mysql_data:
    name: focj_mysql_data

networks:
  focj_network:
    name: focj_network
    driver: bridge