-- 登録申込テーブルに不足しているカラムを追加
ALTER TABLE registrations 
ADD COLUMN IF NOT EXISTS car_number VARCHAR(20),
ADD COLUMN IF NOT EXISTS address_type VARCHAR(20),
ADD COLUMN IF NOT EXISTS relationship_dealer VARCHAR(100),
ADD COLUMN IF NOT EXISTS sales_person VARCHAR(100),
ADD COLUMN IF NOT EXISTS self_introduction TEXT,
ADD COLUMN IF NOT EXISTS referrer1 VARCHAR(100),
ADD COLUMN IF NOT EXISTS referrer_dealer VARCHAR(100),
ADD COLUMN IF NOT EXISTS referrer2 VARCHAR(100);